batch_size: 128
dataset_names:
- cub200
epochs: 1
feature_sizes:
- 16
- 32
- 64
- 128
- 256
- 512
- 1024
- 2048
learning_rate: 0.0008
seed_value: 42
start_time: 2023-10-06_08-30-48
use_early_stopping: true
