DEBUG_MODE: true
batch_size: 32
dataset_names:
- cub200
epochs: 1
feature_sizes:
- 8
learning_rate: 1.0e-05
optimizer: Adam
saved weights: /media/alabutaleb/09d46f11-3ed1-40ce-9868-932a0133f8bb/data/resnet50_finetuned/experiment_gpu_0/weights
scheduler: CosineAnnealingLRWrapperWithWarmup
seed_value: 42
start_time: 2023-10-31_11-28-17
use_early_stopping: true
weight_decay: 2.0e-05
