batch_size: 128
dataset_names:
- cub200
epochs: 750
feature_sizes:
- 8
- 16
- 32
- 64
- 128
- 256
- 512
- 1024
- 2048
learning_rate: 0.0003
seed_value: 42
start_time: 2023-10-18_19-45-53
use_early_stopping: false
weight_decay: 2.0e-05
