batch_size: 16
dataset_names:
- cub200
epochs: 1
feature_sizes:
- 16
- 32
- 64
- 128
- 256
- 512
- 1024
- 2048
learning_rate: 0.0005
seed_value: 42
start_time: 2023-10-07_13-19-51
use_early_stopping: false
weight_decay: 2.0e-05
