DEBUG_MODE: false
batch_size: 256
dataset_names:
- cub200
epochs: 2
feature_sizes:
- 2048
learning_rate: 0.1
optimizer: Adam
saved weights: /media/alabutaleb/09d46f11-3ed1-40ce-9868-932a0133f8bb/data/resnet50_finetuned/experiment_gpu_0/weights
scheduler: CosineAnnealingLRWrapperWithWarmup
seed_value: 42
start_time: 2023-11-02_19-47-48
use_early_stopping: true
weight_decay: 2.0e-05
